bounswe/bounswe2023group6

- practice-app/.env.example
- practice-app/app/templates/base.html
- practice-app/app/templates/index.html
- practice-app/app/templates/worldtime.html
- practice-app/app/views.py
Finally, we will store login passwords as hashed passwords shown below. This task comes from this [issue](https://github.com/bounswe/bounswe2023group6/issues/179).
> added hashed-password

- practice-app/app/templates/worldtime.html
- practice-app/tests/test_worldtime.py
There are changed front end of world time endpoint and unit tests about world time.
> Frontend worldtime ahmetkudu

- practice-app/app/game_information_api.py
- practice-app/tests/test_game_information.py
Added test for testing get_game_information(get), get_game_information(post), add_game_to_favorites, show_all_favorites endpoints. 
Closes #197.
> Added tests for get game information API

- practice-app/tests/test_dnd_api.py
I added tests for dnd_api. I think there is no conflict with main. Closes #203
> added test_dnd_api

- practice-app/app/bored_api.py
I have added Swagger related functionality to my endpoints.
> add swagger functionality

- practice-app/app/worldcountries.py
I added swagger support for my functionality could you please review it and merge to the main branch
> swagger added

- practice-app/app/game_information_api.py
Swagger added for game information API
> Swagger added for game information

- app/mobile/lib/data/models/base_model.dart
- app/mobile/lib/data/models/dto/base_dto_object.dart
- app/mobile/lib/data/models/dto/login/login_request.dart
- app/mobile/lib/data/models/dto/login/login_response.dart
- app/mobile/lib/data/models/login_model.dart
- app/mobile/lib/data/services/base_service.dart
- app/mobile/lib/utils/validation_util.dart
- app/mobile/pubspec.lock
- app/mobile/pubspec.yaml
PR for issue #276 :
- base model, dto and service classes added
- validation util and policies added
> [Mobile] Base model, dto and service classes

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/ExampleController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/controller/HamburgerController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Hamburger.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/HamburgerRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/HamburgerService.kt
---
- **Endpoint:** `/hamburgers`
- **Method:** `GET`
- **Description:** Fetches a list of all hamburgers.
- **Response:** A JSON array of hamburgers.
---
- **Endpoint:** `/hamburgers`
- **Method:** `POST`
- **Description:** Creates a new hamburger.
- **Payload:** JSON object containing hamburger details.
```json
{
"name": "string",
"ingredients": "string",
"price": 0.0
}
```
- **Response:** A JSON object of the created hamburger.
---
- **Endpoint:** `/hamburgers/{id}`
- **Method:** `GET`
- **Description:** Fetches a hamburger by its ID.
- **Path Variable:** `{id}` – The ID of the hamburger to retrieve.
- **Response:** A JSON object of the fetched hamburger.
---
- **Endpoint:** `/hamburgers/{id}`
- **Method:** `PUT`
- **Description:** Updates a hamburger by its ID.
- **Path Variable:** …
> example endpoints with all crud functionalities implemented

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/AccessController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/User.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/exception/CustomExceptions.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/exception/GlobalExceptionHandler.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/ChangePasswordRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/AccessService.kt
- app/backend/src/main/resources/application.properties
Provided that the user shall login, and enter the old password(current password) and two new same passwords.
> implemented the change password feature.

- app/backend/src/main/kotlin/com/gamelounge/backend/model/RegisterationRequest.kt
Changed the data type of profile image from ByteArray to ByteArray? in the request model for registration. Now the users are note obliged to provide a profile image while  registering.
> HOTFIX change RegisterationRequest model

- app/backend/dockerfile
- app/docker-compose.yml
- app/frontend/dockerfile
Docker files added for frontend, backend and whole project.
> Ci cd/enhancement/dockerization deployment

- app/mobile/lib/presentation/pages/login_page.dart
> uptade session fixed

- app/frontend/src/App.js
- app/frontend/src/components/Sidebar.js
- app/frontend/src/components/SubMenu.js
- app/frontend/src/pages/Auth/Login.js
- app/frontend/src/pages/Auth/ResetPassword.js
- app/frontend/src/pages/Auth/index.js
- Implemented a basic logout logic
- Refactored reset password
> Implement logout + refactor change password

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/UserController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/UserService.kt
Implemented endpoints for getting user info using either sessionId or username.
> #339 implement endpoint and service for user info

- app/frontend/.env.example
- app/frontend/.gitignore
- app/frontend/src/components/Sidebar.js
- app/frontend/src/pages/Auth/ForgotPassword.js
- app/frontend/src/pages/Auth/Login.js
- app/frontend/src/pages/Auth/ResetPassword.js
- app/frontend/src/pages/Auth/Signup.js
The profile pictures in the homepage was problematic. This PR (hopefully fixes it).
> Fix picture bug

- app/backend/README.md
Backend docker build and run instructions added
> [BE] docker build and run instructions

- app/mobile/lib/constants/network_constants.dart
- app/mobile/lib/data/models/dto/user/user_detailed_response.dart
- app/mobile/lib/data/models/game_model.dart
- app/mobile/lib/data/models/post_model.dart
- app/mobile/lib/data/models/user_model.dart
- app/mobile/lib/data/services/user_authentication_service.dart
- app/mobile/lib/main.dart
- app/mobile/lib/presentation/pages/game_page.dart
- app/mobile/lib/presentation/pages/home_page.dart
- app/mobile/lib/presentation/pages/profile_page.dart
- app/mobile/lib/presentation/widgets/avatar_widget.dart
- app/mobile/lib/presentation/widgets/drawer_widget.dart
- app/mobile/lib/presentation/widgets/game_card_widget.dart
- app/mobile/lib/presentation/widgets/post_card_widget.dart
- game model and post model added
- user detailed response added
- user details mock service added
- game, post and avatar widget added
- profile page added
> [Mobile] Profile page with some other changes

- app/mobile/lib/presentation/pages/profile_page.dart
Initial profile page implementation is completed. Detailed explanations are in the issue #363
> [Mobile] profile page initial complete implementation

- app/mobile/android/app/src/debug/AndroidManifest.xml
- app/mobile/android/app/src/main/AndroidManifest.xml
- app/mobile/lib/data/models/dto/register/register_request.dart
- app/mobile/lib/data/models/dto/register/register_response.dart
- app/mobile/lib/data/services/user_authentication_service.dart
- app/mobile/lib/presentation/pages/forgot_password_page.dart
- app/mobile/lib/presentation/pages/login_page.dart
- app/mobile/lib/presentation/pages/registration_page.dart
- app/mobile/lib/presentation/widgets/form_widget.dart
- app/mobile/lib/utils/validation_utils.dart
* register request changed from http to dio and register model created.
* register validation error messages added for textfields
* name and surname forms are removed
* confirm password added
#361
> [Mobile] Register page improved

- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Comment.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Game.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/LFG.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Post.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Tag.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/User.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/RegisterationRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/AccessService.kt
- app/backend/src/main/resources/application.properties
All entities are created and tested. They behave as expected, ready to merge to dev branch.
> Backend/enhancement/refactor entities #391

- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Game.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/LFG.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Post.kt
Added related games to both LFGs and Posts.
> HOTFIX add related games to posts and lfgs

- app/mobile/lib/data/models/comment_model.dart
- app/mobile/lib/data/models/content_model.dart
- app/mobile/lib/data/models/dto/content/post_create_dto_request.dart
- app/mobile/lib/data/models/dto/content/post_create_dto_response.dart
- app/mobile/lib/data/services/post_service.dart
- app/mobile/lib/main.dart
- app/mobile/lib/presentation/pages/forum_page.dart
- app/mobile/lib/presentation/pages/home_page.dart
- app/mobile/lib/presentation/pages/post_page.dart
- app/mobile/lib/presentation/widgets/post_card_widget.dart
Initial implementation for post page added. More details will be in the related issue #387
> [Mobile] post page initial implementation

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/AccessController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/controller/PostController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/controller/UserController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Game.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/LFG.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/User.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/CommentDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/GameDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/LFGDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/PostDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/TagDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/UserDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/RegisterationRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/ChangePasswordRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/ForgotPasswordRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/LoginRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/RegisterationRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/ResetPasswordRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/UpdateUserRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/response/GetUserInfoResponse.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/GameRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/LFGRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/PostRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/TagRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/UserRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/AccessService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/UserService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/util/ConverterDTO.kt
- app/backend/src/test/kotlin/com/gamelounge/backend/AccessServiceTest.kt
Implemented profile page related endpoints and changes response models to DTOs.
> Backend/enhancement/implement profile page related endpoints #403

- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Post.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Report.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/ReportDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/PostRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/TagRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/util/ConverterDTO.kt
- app/backend/src/main/resources/application.properties
We worked on this issue collectively with @ohbahadiroglu . Initialized the report and like features, and also disabled flyway. Also some classes needed fixes related to nullability, we also took care of that.
> Backend/enhancement/report like features #437

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/UserController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Report.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/UpdateUserRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/UserRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/UserService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/util/ConverterDTO.kt
Implemented endpoints to access the liked posts and the comments of the user.  Also fixed some minor problems related to the Report entity. 
Other than that I also added the authentication layer to the profile page endpoints. That way the possible request coming to our backend service other than the frontend and the mobile applications will be discarded in the absence of a sessionId.
>  [Backend] #403 enhance profile related endpoints

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/TagController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Tag.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/TagRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/TagService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/UserService.kt
I implemented the features described in the #446. I tested in my local, created the related postman queries.
> [Backend]  #446 Backend/enhancement/implement tag related functions

- app/mobile/lib/data/models/game_model.dart
- app/mobile/lib/data/services/game_service.dart
- app/mobile/lib/main.dart
- app/mobile/lib/presentation/pages/game_wiki_page.dart
- app/mobile/lib/presentation/pages/main_screen.dart
- app/mobile/lib/presentation/pages/navigator.dart
- app/mobile/lib/presentation/pages/profile_page.dart
- app/mobile/lib/presentation/states/game_list_grid_view_state.dart
- app/mobile/lib/presentation/widgets/drawer_widget.dart
- Nested navigation with a bottom navigation bar
- Maintain the state of the BottomNavigationbar across tabs
- Navigator added
#431
> [Mobile] Persistent navigation bar

- app/mobile/lib/data/services/user_authentication_service.dart
- app/mobile/lib/presentation/pages/game_wiki_page.dart
- app/mobile/pubspec.lock
- app/mobile/pubspec.yaml
Game page related posts part added
#429
> [Mobile] Game page related posts part added

- app/mobile/lib/constants/network_constants.dart
- app/mobile/lib/data/models/dto/game/game_request.dart
- app/mobile/lib/data/models/dto/game/game_response.dart
- app/mobile/lib/data/models/dto/game/multiple_game_dto_response.dart
- app/mobile/lib/data/models/game_model.dart
- app/mobile/lib/data/services/game_service.dart
- app/mobile/lib/presentation/pages/game_wiki_page.dart
- Initial game service created
- Initial get game service implemented
- Initial get games service implemented
- Game Page Future Builder implemented
- Additional Game Informations added
#430 
When backend implement game service, there will be update.
> [Mobile] initial game service

- app/frontend/src/pages/Profile/LikedPosts.js
- app/frontend/src/pages/Profile/ProfileMenu.js
- app/frontend/src/pages/Profile/ProfilePage.js
I added a menu where users can navigate liked posts, created posts, liked comments and created comments of profile owner.
> [Frontend] Improve profile page

- app/mobile/lib/constants/network_constants.dart
- app/mobile/lib/data/models/character_model.dart
- app/mobile/lib/data/models/dto/game/game_create_dto_request.dart
- app/mobile/lib/data/models/dto/game/game_response.dart
- app/mobile/lib/data/models/game_model.dart
- app/mobile/lib/data/services/base_service.dart
- app/mobile/lib/data/services/game_service.dart
- app/mobile/lib/data/services/post_service.dart
- app/mobile/lib/data/services/user_service.dart
- app/mobile/lib/presentation/pages/game_page_create.dart
- app/mobile/lib/presentation/pages/game_wiki_page.dart
- app/mobile/lib/presentation/pages/main_screen.dart
- app/mobile/lib/presentation/pages/post/post_create_page.dart
- app/mobile/lib/presentation/states/game_list_grid_view_state.dart
- app/mobile/lib/presentation/widgets/game_card_widget.dart
- app/mobile/lib/presentation/widgets/vertical_game_card_widget.dart
- app/mobile/linux/flutter/generated_plugin_registrant.cc
- app/mobile/linux/flutter/generated_plugins.cmake
- app/mobile/macos/Flutter/GeneratedPluginRegistrant.swift
- app/mobile/pubspec.lock
- app/mobile/pubspec.yaml
- app/mobile/windows/flutter/generated_plugin_registrant.cc
- app/mobile/windows/flutter/generated_plugins.cmake
> [Mobile] create game page service

- app/frontend/src/components/CommentCard.js
- app/frontend/src/components/PostCard.js
> [Frontend] Report Button

- app/mobile/lib/data/models/content_model.dart
- app/mobile/lib/data/models/dto/content/post_create_dto_request.dart
- app/mobile/lib/data/models/post_model.dart
- app/mobile/lib/data/services/post_service.dart
- app/mobile/lib/presentation/pages/post/content_card_widget.dart
- app/mobile/lib/presentation/pages/post/post_create_page.dart
- app/mobile/lib/presentation/widgets/post_card_widget.dart
- app/mobile/pubspec.lock
- app/mobile/pubspec.yaml
Solves issue #521. More details will be provided in the issue.
> [Mobile] post page date tags categories

- app/frontend/src/components/PostCard.js
- app/frontend/src/pages/ForumPage/EditPost.js
- app/frontend/src/pages/ForumPage/index.js
I added post editing section. By using that, users can edit their posts.
> Edit Post Functionality

- app/frontend/src/components/navbar/Navbar.js
Login and signup buttons added if user is not logged in.
> login check feature added

- app/mobile/lib/presentation/pages/forum_page.dart
Posts are sorted in time descending order. (Latest comes first)
> [Mobile] Sorting posts

- app/mobile/lib/presentation/pages/game_page_create.dart
- app/mobile/lib/presentation/pages/game_wiki_page.dart
Update page implemented. Service connection and update functionality is lack right now. Related issue can be found [here](https://github.com/bounswe/bounswe2023group6/issues/525).
> Update page implemented.

- app/frontend/src/components/PostCard.js
- app/frontend/src/pages/ForumPage/CreatePost.js
- app/frontend/src/pages/ForumPage/ForumPage.js
- I added filtering post functionality according to post categories.
- I fixed tag selection when creating post and made tags appear on posts.
> [Frontend] category filter in forum page

- app/backend/src/main/kotlin/com/gamelounge/backend/constant/Enumerations.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Game.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/GameDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/CreateGameRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/UpdateGameRequest.kt
Created a separate Kotlin file named `Enumerations.kt` to house the enumerations related to the `Game` entity. Those enums are GameGenre, GamePlatform, NumberOfPlayers, UniverseInfo, and GameMechanics.
Modified `Game.kt` to reference these enumerations from the new `Enumerations.kt` file.
The enumerations representing game-related attributes have been organized into a dedicated file, `Enumerations.kt`. This enhances code maintainability and separation of concerns. 
Since static values can now be given for game fields, we will be able to make recommendations based on them.
Codebase is now more modular, making it easier to manage and extend the game-related enumerations.
> completed creating game field enumerations

- app/backend/src/main/kotlin/com/gamelounge/backend/BackendApplication.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/controller/AccessController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Game.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/User.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/exception/CustomExceptions.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/exception/GlobalExceptionHandler.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/GameDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/RegisterationRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/response/GetUserInfoResponse.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/GameRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/GameService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/util/ConverterDTO.kt
Added code to create an initial admin user when the application starts. This practice ensures a secure system initialization and prevents users from creating admin accounts through exposed endpoints.
Included a new field, isAdmin, in the User entity to distinguish admin users.
The isAdmin field is not included in the UserDTO to prevent users from manipulating the creation of admin accounts through request payloads.
Added new endpoints for managing admin tasks related to game approval and rejection.
Implemented the following admin-specific endpoints:
- GET /admin/pendingGames: Retrieves a list of pending games for admin review.
- PUT /admin/approveGame/{gameId}: Approves a pending game.
- PUT /admin/rejectGame/{gameId}: Rejects a pending game.
These changes improve the security and …
> Completed Basic Admin Approval Mechanism

- reports/lab_report_9.md
> lab report 9 is added

- app/frontend/src/components/CommentCard.js
- app/frontend/src/components/PostCard.js
- app/frontend/src/pages/ForumPage/CreatePost.js
- app/frontend/src/pages/ForumPage/ForumPage.js
- app/frontend/src/pages/ForumPage/SelectTags.js
- app/frontend/src/pages/GameForum/CreateGame.js
- app/frontend/src/pages/GameForum/GameForum.js
- app/frontend/src/pages/GamePage/CreateGame.js
- app/frontend/src/pages/GamePage/GamePage.js
- app/frontend/src/pages/HomePage/Game.js
- app/frontend/src/pages/HomePage/Group.js
- app/frontend/src/pages/HomePage/HomePage.js
- app/frontend/src/pages/HomePage/Post.js
- app/frontend/src/pages/HomePage/Suggestion.js
- app/frontend/src/pages/PostPage/PostPage.js
I modified styling, also added;
- post filtering section according to post categories and tags
- sort button in ascending or descending order according to post creation date
> [Frontend] Forum post sorting and filtering

- app/mobile/lib/constants/network_constants.dart
- app/mobile/lib/data/models/dto/game/game_create_dto_request.dart
- app/mobile/lib/data/services/game_service.dart
- app/mobile/lib/presentation/pages/game_page_create.dart
- app/mobile/lib/presentation/pages/game_wiki_page.dart
implemented rate game service.
implemented update game service.
field types updated based on backend.
this pr related with issues #526 #551
> Implemet game page missing parts

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/AccessController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/controller/GameController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/controller/PostController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/controller/UserController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Report.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/RequestedEditingGame.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/Session.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/User.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/exception/CustomExceptions.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/exception/GlobalExceptionHandler.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/EditedGameDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/ReportDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/UserDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/CreateEditingRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/UpdateUserRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/EditedGameRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/PostRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/SessionRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/UserRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/GameService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/PostService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/UserService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/util/ConverterDTO.kt
This pull request focuses on backend enhancements to meet specific requirements related to user profiles, forum functionality, and game pages.
**View Other User Profiles (1.1.2.2):**
Implemented backend functionality for users to view profiles of other users.
Added visibility checks to provide only visible profiles.
**Delete User Profile (1.1.2.3):**
Implemented backend logic for users to delete their own profile pages.
**Edit Profile Visibility (1.1.2.7):**
Implemented backend support for users to edit their profile status (visibility).
**Follow Other Users (1.1.3.1.2):**
Implemented backend functionality for users to follow other users.
**Filter Post Categories in Forum (1.1.3.2.17):**
Implemented backend support for users to filter post categories in the forum.
**Request Game Page …
> completed the issue no 559

- app/mobile/lib/data/models/annotation_model.dart
- app/mobile/lib/presentation/pages/post/content_card_widget.dart
- app/mobile/lib/presentation/widgets/annotatable_text_widget.dart
I have added the initial implementation of annotation widget. 
With these pr: 
- Annotation model created
- Annotation widget created
- Creating annotation dialog added
- Showing multiple annotations dialog added
It has some missing properties such as: 
- backend connections
- Supporting different annotation models
- Image annotations
> [Mobile] annotation feature initial implementation

- app/mobile/lib/presentation/pages/main_screen.dart
- app/mobile/lib/presentation/pages/navigator.dart
Little fix for multiple widgets use same global key error
- unique key added for navigator
> [Mobile] multiple widgets use same global key error

- app/frontend/src/pages/ForumPage/ForumPage.js
- app/frontend/src/pages/ForumPage/SelectTags.js
- app/frontend/src/pages/Profile/EditProfile.js
- app/frontend/src/services/postService.js
On profile edit section, the problem of data not being visible has been solved.
Backend connection of the tags has been made on the forum page page.
> [Frontend] Missing parts are added.

- app/frontend/src/components/CommentCard.js
- app/frontend/src/components/PostCard.js
- app/frontend/src/pages/ForumPage/EditPost.js
- app/frontend/src/pages/ForumPage/ForumPage.js
- app/frontend/src/pages/GameForum/GameForum.js
- app/frontend/src/pages/GamePage/GamePage.js
- app/frontend/src/pages/PostPage/PostPage.js
- Upvote/downvote functionality fixed
- Edit and report button permissions are fixed
> [Frontend] Fix forum post operations

- .github/workflows/backend_build.yml
- .github/workflows/frontend_build.yml
When a push comes to develop branch, it should trigger the ci/cd pipeline.
> Push based trigger and continuous deployment added

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/UserController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/User.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/response/GetUserInfoResponse.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/UserService.kt
- app/backend/src/test/kotlin/com/gamelounge/backend/GameServiceTest.kt
- app/backend/src/test/kotlin/com/gamelounge/backend/UserServiceTest.kt
- follower count added in user model
- new required fields added to get user info response
- profile page related endpoints added for other users
- follow related fixes and follower count addition
- test fixes
> [Backend] user response addition and fixes

- app/mobile/lib/data/models/annotation_model.dart
- app/mobile/lib/data/models/dto/annotation/annotation_dto.dart
- app/mobile/lib/data/models/dto/annotation/multiple_annotation.dart
- app/mobile/lib/data/services/annotation_service.dart
- app/mobile/lib/presentation/widgets/annotatable_image_widget.dart
- app/mobile/lib/presentation/widgets/annotatable_text_widget.dart
- app/mobile/lib/presentation/widgets/crop_image_widget.dart
Following changes are made: 
- json-ld conversion added for annotation models
- annotation services and dto objects implemented
- Little fixes to annotation image widget
> [Mobile] json-ld format conversion added for annotation

- app/mobile/lib/constants/network_constants.dart
- app/mobile/lib/data/models/user_model.dart
- app/mobile/lib/data/services/admin_service.dart
- app/mobile/lib/main.dart
- app/mobile/lib/presentation/pages/admin_game_page.dart
- app/mobile/lib/presentation/pages/admin_panel.dart
- app/mobile/lib/presentation/pages/login_page.dart
- app/mobile/lib/presentation/widgets/drawer_widget.dart
Admin panel implemented for approving and rejecting created game pages
for issue #545.
> [Mobile] Initial admin panel implemented

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/CommentController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/controller/LFGController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/LFG.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/exception/CustomExceptions.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/exception/GlobalExceptionHandler.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/LFGDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/CreateLFGRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/UpdateLFGRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/LFGRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/CommentService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/LFGService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/util/ConverterDTO.kt
- create and update request models implemented
- custom exceptions and handlers implemented for lfg
- LFGDTO realteds implemented
- made small refactors for LFG entity
- controller, service and repo layers implemented for lfg
- comment system on lfgs implemented
> Backend/enhancement/lfg section endpoints#562

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/UserController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/PostService.kt
Added endpoints for accessing other users' liked posts, created posts, created games, and liked comments,
> #662 add endpoints for accessing other user's info

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/UserController.kt
Removed some endpoints in the user controller that caused ambiguity.
> HOTFIX remove ambiguous endpoints from UserController

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/SearchController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/response/SearchResults.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/GameRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/LFGRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/PostRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/SearchService.kt
games, posts and lfgs are searchable with seperate endpoints. There is also a searchAll endpoint which searchs all.
> search functionality implemented

- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/PostDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/CreatePostRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/request/UpdatePostRequest.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/PostService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/util/ConverterDTO.kt
> post-game relation activated

- app/backend/src/main/kotlin/com/gamelounge/backend/util/ConverterDTO.kt
- app/frontend/src/components/CommentCard.js
- app/frontend/src/components/PostCard.js
- app/frontend/src/components/SubMenu.js
- app/frontend/src/pages/PostPage/PostPage.js
- app/frontend/src/services/commentService.js
- app/frontend/src/services/gameService.js
- app/frontend/src/services/gameServise.js
- app/frontend/src/services/postService.js
- app/frontend/src/services/userService.js
> [Frontend] Implement remove post

- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/UserGameRatingDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/response/GetUserInfoResponse.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/UserService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/util/ConverterDTO.kt
> HOTFIX remove conflicts

- app/mobile/lib/data/models/content_model.dart
- app/mobile/lib/data/models/lfg_model.dart
- app/mobile/lib/data/services/lfg_service.dart
- app/mobile/lib/presentation/pages/group_page.dart
- app/mobile/lib/presentation/pages/post/content_card_widget.dart
- app/mobile/lib/presentation/pages/post/post_page.dart
- app/mobile/lib/presentation/states/lfg_list_grid_view_state.dart
- PostState converted to ContentState for use in lfg page
- lfg model updated to be extended from Content model
- lfg comment section made similar to post page comment section
> [Mobile] Lfg comment section

- app/frontend/src/pages/LfgPage/CreateLfg.js
- app/frontend/src/pages/LfgPage/LfgCard.js
- app/frontend/src/pages/LfgPage/LfgPage.js
- app/frontend/src/services/lfgService.js
> [Frontend] Create Lfg

- app/mobile/lib/presentation/pages/lfg_page_create.dart
- app/mobile/lib/presentation/pages/post/post_create_page.dart
- app/mobile/lib/presentation/widgets/tag_input.dart
I have completed [this](https://github.com/bounswe/bounswe2023group6/issues/594) issue. Tag widget in post create page became modular.
> [Mobile] Tag option lfg

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/AdminController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/exception/CustomExceptions.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/exception/GlobalExceptionHandler.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/repository/ReportRepository.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/ReportService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/util/ConverterDTO.kt
implemented four additional endpoints for admin panel. these endpoints can be used for fetching all reports related to game, lfg, post or comment.
> Backend/enhanemcent/admin panel additional endpoints#633

- app/mobile/lib/data/models/dto/game/game_create_dto_request.dart
- app/mobile/lib/data/models/game_model.dart
- app/mobile/lib/data/services/admin_service.dart
- app/mobile/lib/data/services/game_service.dart
- app/mobile/lib/presentation/pages/admin_game_page.dart
- app/mobile/lib/presentation/pages/game_page_create.dart
- app/mobile/lib/presentation/pages/game_wiki_page.dart
all game model related things updated because game model has changed.
> [Mobile] all game model related things updated

- app/mobile/lib/data/models/dto/user/user_response.dart
- app/mobile/lib/data/models/user_model.dart
- app/mobile/lib/data/services/user_service.dart
- app/mobile/lib/presentation/pages/profile_page.dart
- app/mobile/lib/presentation/widgets/avatar_widget.dart
- tags and visibility added to user model
- follow, unfollow and get followings service connections made
- liked, disliked and created post data connections corrected
- tag, visibility and information sections added to profile
- follow section problems corrected in profile
> [Mobile] Profile page missing fields and backend connection

- app/backend/src/main/kotlin/com/gamelounge/backend/controller/LFGController.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/entity/LFG.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/exception/CustomExceptions.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/exception/GlobalExceptionHandler.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/model/DTO/LFGDTO.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/service/LFGService.kt
- app/backend/src/main/kotlin/com/gamelounge/backend/util/ConverterDTO.kt
- join, leave and kick functionality implemented for lfg
- entity and dto classes refactored for new functionalities
- custom exceptions defined and handlers implemented for errors
> Backend/enhancement/lfg section augmentation#643

- app/frontend/src/pages/LfgPage/EditLfg.js
- app/frontend/src/pages/LfgPage/LfgCard.js
> [Frontend] Edit Lfg

- app/frontend/src/App.js
- app/frontend/src/pages/LfgPage/CreateLfg.js
- app/frontend/src/pages/LfgPage/Lfg.js
- app/frontend/src/pages/LfgPage/LfgCard.js
- app/frontend/src/services/commentService.js
Separate lfg page was created for each lfg
> [Frontend] Add Lfg Page

- app/frontend/src/pages/LfgPage/CreateLfg.js
- app/frontend/src/pages/LfgPage/LfgCard.js
Users can join and leave the lfg.
> [Frontend] Join-leave lfg functionality

- app/frontend/src/components/navbar/Navbar.js
- app/frontend/src/pages/GameForum/GameForum.js
> [Frontend] Fix My Profile Button on Navbar

- app/mobile/lib/presentation/pages/game_page_create.dart
- app/mobile/pubspec.lock
- app/mobile/pubspec.yaml
I have implemented multiple selection for genre and platforms. Related issue can be found [here](https://github.com/bounswe/bounswe2023group6/issues/592).
> [Mobile] Multiple choice gamepage

- app/mobile/lib/data/services/lfg_service.dart
- app/mobile/lib/presentation/pages/game_wiki_page.dart
- app/mobile/lib/presentation/pages/group_page.dart
- app/mobile/lib/presentation/pages/lfg_page_create.dart
Update page implemented. Related issue is [here](https://github.com/bounswe/bounswe2023group6/issues/552).
> [Mobile]Implement update page for lfg.

- app/mobile/lib/data/models/content_model.dart
- app/mobile/lib/main.dart
- app/mobile/lib/presentation/pages/forum_page.dart
- app/mobile/lib/presentation/pages/game_page.dart
- app/mobile/lib/presentation/pages/game_wiki_page.dart
- app/mobile/lib/presentation/pages/lfg_page.dart
- app/mobile/lib/presentation/pages/navigator.dart
- app/mobile/lib/presentation/pages/opening_page.dart
- app/mobile/lib/presentation/pages/post/post_page.dart
- app/mobile/lib/presentation/states/lfg_list_grid_view_state.dart
- app/mobile/lib/presentation/widgets/post_card_widget.dart
Related issue can be found [here](https://github.com/bounswe/bounswe2023group6/issues/587).
> [Mobile] Guest user implemented.

- app/backend/src/test/kotlin/com/gamelounge/backend/CommentServiceTest.kt
- app/backend/src/test/kotlin/com/gamelounge/backend/GameServiceTest.kt
- app/backend/src/test/kotlin/com/gamelounge/backend/PostServiceTest.kt
- app/backend/src/test/kotlin/com/gamelounge/backend/UserServiceTest.kt
completed the unit tests about Game service
> Completed-GameServiceTest-UnitTest

- app/mobile/lib/data/models/dto/lfg/lfg_create_dto_request.dart
- app/mobile/lib/data/models/dto/lfg/lfg_response.dart
- app/mobile/lib/data/models/dto/lfg/mutliple_lfg_dto_request.dart
- app/mobile/lib/data/models/lfg_model.dart
- app/mobile/lib/data/services/game_service.dart
- app/mobile/lib/data/services/lfg_service.dart
- app/mobile/lib/presentation/pages/lfg_page_create.dart
- app/mobile/lib/presentation/states/game_list_grid_view_state.dart
- app/mobile/lib/presentation/states/lfg_list_grid_view_state.dart
- app/mobile/lib/presentation/widgets/lfg_card_widget.dart
Related issue is [here](https://github.com/bounswe/bounswe2023group6/issues/548).
> [Mobile] Create LFG Service

- app/frontend/src/pages/HomePage/Group.js
- app/frontend/src/pages/LfgPage/EditLfg.js
- app/frontend/src/pages/LfgPage/Lfg.js
- app/frontend/src/pages/LfgPage/LfgCard.js
- app/frontend/src/pages/LfgPage/LfgPage.js
Only group members will be able to add comments to lfgs.
> [Frontend] Lfg Comment Fix

- app/mobile/lib/data/models/game_model.dart
- app/mobile/lib/data/services/game_service.dart
- app/mobile/lib/data/services/post_service.dart
- app/mobile/lib/presentation/pages/game_wiki_page.dart
- app/mobile/lib/presentation/pages/home_page.dart
- endpoints for recommended posts and games added
- get all usages converted to get recommended(home page and game wiki page)
- similar game ids added to game model
> [Mobile] Recommendation implementation

- app/mobile/lib/presentation/pages/forum_page.dart
- app/mobile/lib/presentation/pages/game_page.dart
- app/mobile/lib/presentation/pages/game_wiki_page.dart
- app/mobile/lib/presentation/pages/home_page.dart
- app/mobile/lib/presentation/pages/lfg_page.dart
- app/mobile/lib/presentation/states/lfg_list_grid_view_state.dart
- app/mobile/lib/presentation/widgets/guest_control_widget.dart
- app/mobile/lib/presentation/widgets/post_card_widget.dart
- app/mobile/lib/utils/cache_manager.dart
- guest control widget added
- is user logged in notifier added
- all guest related controls converted to guest control widget
> [Mobile] Guest control fixes

- app/annotation-service/build.gradle.kts
- app/annotation-service/src/main/kotlin/com/group6/annotationservice/Utils/DtoConverter.kt
- app/annotation-service/src/main/kotlin/com/group6/annotationservice/service/AnnotationService.kt
- app/annotation-service/src/test/kotlin/com/group6/annotationservice/AnnotationControllerTests.kt
- app/annotation-service/src/test/kotlin/com/group6/annotationservice/AnnotationServiceTests.kt
Annotation Service was implemented and unit tests were missing for the reliability of the service. In this PR unit tests are added.
> Implement Unit Tests for Annotation Service 
